language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
    - 3.6

env:
    global:
        - NUMPY_VERSION=1.12
        - SCIPY_VERSION=0.19
        - CMD='./runtests.py'
        - COVERAGE=0

matrix:
    include:
        - python: 2.7
          env: CMD='./runtests.py --cov-report= --cov=nestle' NUMPY_VERSION=1.9 SCIPY_VERSION=0.16 COVERAGE=1
        - python: 2.7
          env: NUMPY_VERSION=1.6 SCIPY_VERSION=0.11  # py2.7, oldest deps
        - python: 3.3
          env: NUMPY_VERSION=1.7 SCIPY_VERSION=0.13  # py3.3, oldest deps
        - python: 3.6
          env: NUMPY_VERSION=1.12 SCIPY_VERSION=0     # py3.4, no scipy

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

# Note: leave numpy in all `conda install` commands to prevent conda from
# upgrading it automatically.
install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION pytest
    - source activate test
    - if [[ $SCIPY_VERSION > 0 ]]; then conda install --yes numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION; fi
    - if [[ $COVERAGE ]]; then pip install pytest-cov coveralls; fi
    - source activate test
    - python setup.py install

script: $CMD

after_success: if [[ $COVERAGE ]]; then coveralls; fi
